In [3]:
import json
import pandas as pd

results_path = "/content/drive/MyDrive/NIDS/results"

# Load saved metrics
with open(f"{results_path}/logistic_regression_metrics.json", "r") as f:
    lr_results = json.load(f)

with open(f"{results_path}/random_forest_metrics.json", "r") as f:
    rf_results = json.load(f)

with open(f"{results_path}/xgboost_metrics.json", "r") as f:
    xgb_results = json.load(f)

# Combine results
results = [lr_results, rf_results, xgb_results]

comparison_df = pd.DataFrame(results)

comparison_df

,model,accuracy,macro_precision,macro_recall,macro_f1,weighted_f1,training_time_seconds
0,Logistic Regression,0.822227,0.299301,0.875205,0.355227,0.884097,NaN
1,Random Forest,0.998512,0.923361,0.810360,0.842885,0.998452,838.840468
2,XGBoost,0.998907,0.932005,0.836965,0.870408,0.998865,696.715920

In [5]:
comparison_display = comparison_df.copy()

comparison_display["training_time_minutes"] = (
    comparison_display["training_time_seconds"] / 60
).round(2)

for col in [
    "accuracy",
    "macro_precision",
    "macro_recall",
    "macro_f1",
    "weighted_f1"
]:
    comparison_display[col] = comparison_display[col].round(4)

comparison_display = comparison_display[
    [
        "model",
        "training_time_minutes",
        "accuracy",
        "macro_precision",
        "macro_recall",
        "macro_f1",
        "weighted_f1"
    ]
]

comparison_display

,model,training_time_minutes,accuracy,macro_precision,macro_recall,macro_f1,weighted_f1
0,Logistic Regression,NaN,0.8222,0.2993,0.8752,0.3552,0.8841
1,Random Forest,13.98,0.9985,0.9234,0.8104,0.8429,0.9985
2,XGBoost,11.61,0.9989,0.9320,0.8370,0.8704,0.9989